### ISSUE TITLE
When I select a project, can I select the task (TASK_ID) associated with it? 

### ISSUE THREAD

**Issue by Akiyam-hub** [godbout/alfred-time#45]
Your workflow is very easy to use, and I love it!

I recently noticed that Toggl allows you to set a task (tTASK_ID) for a project.
However, when I start a new timer from this workflow and select a project,
However, when I start a new timer from this workflow and select a project, it is bothering me that it is not configurable.

When selecting a project, can I select the task (TASK_ID) associated with it?

Thanks in advance.

P.S.

I posted this once, but accidentally closed it.
I'm going to ask it again.

**Comment by godbout** [comment]
yeah, i think you're referring to #26. never took the time to do it tho, because i personally mostly only use the `continue a timer` functionality. this Workflow supports i think four services for now, so that would require to check if each of them supports this first. definitely not in my priority list. but PR possible!

**Comment by Akiyam-hub** [comment]
Thanks for replying! I'll keep an eye out for future developments!
